// analyze.js — pure, framework-free heuristics for passive cross-identity
// IDOR / BAC (BOLA / BFLA) triage over HTTP history the collector already
// captured. No network access, no replay, no mutation of requests: every
// function here only reads the request/response pairs panel.js hands it.
//
// This is intentionally a companion to Reconner's server-side active authz
// engine (internal/scanner/authz*.go, identity.go), not a replacement for
// it: the server proves a finding by replaying a resource across identities
// live against the target. This module only flags *candidates worth
// replaying/verifying*, from traffic a human tester already generated by
// switching identity label and browsing normally — mirroring the same
// "two identities required to prove cross-user access" rule the backend
// IDOR scanner uses (see internal/scanner/idor.go), applied passively.
//
// Kept dependency-free and side-effect-free so it can run unmodified in the
// DevTools panel (browser) and under `node --test` (see ../test/).

export const DEFAULT_ID_PARAM_NAMES = new Set([
  'id', 'uuid', 'guid', 'uid', 'pk', 'key',
  'userid', 'user_id', 'accountid', 'account_id', 'ownerid', 'owner_id',
  'orderid', 'order_id', 'invoiceid', 'invoice_id', 'ticketid', 'ticket_id',
  'fileid', 'file_id', 'docid', 'doc_id', 'documentid', 'document_id',
  'recordid', 'record_id', 'itemid', 'item_id', 'productid', 'product_id',
  'customerid', 'customer_id', 'memberid', 'member_id', 'profileid', 'profile_id',
  'orgid', 'org_id', 'organizationid', 'organization_id', 'teamid', 'team_id',
  'projectid', 'project_id', 'groupid', 'group_id', 'contactid', 'contact_id',
])

// Names that look like identifiers but are volatile per-request material
// (anti-CSRF tokens, session/nonce values, pagination/sort noise) — never
// treated as an *object* reference, named or unnamed.
const EXCLUDED_NAME_RE = /(^|[-_])(csrf|xsrf|token|nonce|timestamp|ts|session|sessionid|access[-_]?token|refresh[-_]?token|authenticity[-_]?token|state|redirect|callback|page|limit|offset|size|per[-_]?page|pagesize|count|top|skip|sort|order|cursor|year|month|day)($|[-_])/i

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const OBJECTID_RE = /^[0-9a-f]{24}$/i
const DIGITS_RE = /^\d+$/
const OPAQUE_HEX_RE = /^[0-9a-f]{16,}$/i

/** Does this bare value look like an object identifier at all (any shape)? */
export function looksLikeIdValue(raw) {
  if (raw == null) return false
  const v = String(raw)
  if (!v || v.length > 64) return false
  return DIGITS_RE.test(v) || UUID_RE.test(v) || OBJECTID_RE.test(v) || OPAQUE_HEX_RE.test(v)
}

/** Is this parameter/field *name* the kind that usually holds an object reference? */
export function isIdParamName(name, extra) {
  if (!name) return false
  const n = String(name).toLowerCase()
  // An explicit "*_id" / "id" suffix is a stronger, more specific signal
  // than the generic pagination/volatile word list, so it wins first —
  // otherwise legitimate object-id fields like "order_id", "page_id" or
  // "state_id" would be wrongly excluded just because "order"/"page"/
  // "state" are also common *standalone* sort/pagination param names.
  if (/(^|_)id$/.test(n)) return true
  if (DEFAULT_ID_PARAM_NAMES.has(n)) return true
  if (extra && extra.has(n)) return true
  if (EXCLUDED_NAME_RE.test(n)) return false
  return false
}

/** Replace id-shaped path segments with `{id}` so same-shape endpoints group together. */
export function templatePath(pathname) {
  return pathname
    .split('/')
    .map(seg => (seg && looksLikeIdValue(seg) ? '{id}' : seg))
    .join('/')
}

/**
 * Path segments worth using as *concrete-object* signal. Bare 1–2 digit
 * segments are excluded — they are far more often a page/step/tab number
 * than a real object id, and including them causes false positives when
 * two identities independently paginate to the same page.
 */
export function pathIdSegments(pathname) {
  return pathname.split('/').filter(seg => {
    if (!seg) return false
    if (DIGITS_RE.test(seg)) return seg.length >= 3
    return UUID_RE.test(seg) || OBJECTID_RE.test(seg) || OPAQUE_HEX_RE.test(seg)
  })
}

/** Id-shaped query parameters, named (any shape) or unnamed (non-numeric shapes only, for the same pagination-safety reason as pathIdSegments). */
export function queryIdSignals(searchParams, extraIdParams) {
  const out = []
  for (const [name, value] of searchParams.entries()) {
    if (!value) continue
    if (isIdParamName(name, extraIdParams) && looksLikeIdValue(value)) {
      out.push(`${name}=${value}`)
    } else if (!EXCLUDED_NAME_RE.test(name) && !DIGITS_RE.test(value) && looksLikeIdValue(value)) {
      out.push(`${name}=${value}`)
    }
  }
  return out
}

/** Id-shaped fields inside a (bounded) JSON response body. */
export function bodyIdSignals(text, mimeType, extraIdParams, cap = 300) {
  if (!text || !(mimeType || '').toLowerCase().includes('json')) return []
  let data
  try { data = JSON.parse(text) } catch { return [] }
  const out = []
  let budget = cap
  const walk = (value, depth) => {
    if (budget <= 0 || depth > 3) return
    if (Array.isArray(value)) {
      for (const v of value) { if (budget <= 0) break; walk(v, depth + 1) }
      return
    }
    if (value && typeof value === 'object') {
      for (const [k, v] of Object.entries(value)) {
        if (budget-- <= 0) return
        if ((typeof v === 'string' || typeof v === 'number') && isIdParamName(k, extraIdParams) && looksLikeIdValue(v)) {
          out.push(`${k}=${v}`)
        } else if (v && typeof v === 'object') {
          walk(v, depth + 1)
        }
      }
    }
  }
  walk(data, 0)
  return [...new Set(out)]
}

// Same denial vocabulary the backend authz engine uses
// (internal/scanner/idor.go:idorErrorSignatures) so a passive candidate and
// an active proof agree on what "denied" looks like.
const ERROR_SIGNATURES = [
  'not found', 'forbidden', 'access denied', 'unauthorized', 'permission',
  '404', '403', '401', 'please log in', 'sign in', 'login required',
]

export function looksLikeErrorBody(text) {
  if (!text) return false
  const lower = text.slice(0, 2000).toLowerCase()
  return ERROR_SIGNATURES.some(sig => lower.includes(sig))
}

/**
 * success | denied | unknown, from status + a cheap look at the body.
 * A 200 with a hollow or error-shaped body is treated as a soft denial —
 * plenty of APIs answer "forbidden" with HTTP 200.
 */
export function classifyOutcome(status, bodyLen, bodyText) {
  if (!status) return 'unknown'
  if ([401, 403, 404, 407, 429].includes(status)) return 'denied'
  if (status >= 300 && status < 400) return 'denied'
  if (status >= 500) return 'unknown'
  if (status >= 200 && status < 300) {
    // Only treat a 2xx as a soft denial when the body is next to nothing —
    // real APIs routinely return small-but-genuine objects (e.g. `{"id":42}`
    // is 10 bytes), so this must stay far below the ~100+ byte thresholds
    // that make sense for a full authenticated page.
    if (status !== 204 && bodyLen < 8) return 'denied'
    if (bodyText && bodyLen < 4096 && looksLikeErrorBody(bodyText)) return 'denied'
    return 'success'
  }
  return 'unknown'
}

const PII_KEY_RE = /"(email|e[-_]?mail|phone|mobile|ssn|national_id|address|full[-_]?name|first[-_]?name|last[-_]?name|dob|date_of_birth|credit_card|card_number|iban|account_number)"\s*:/i
export function looksSensitiveBody(text) {
  return !!text && PII_KEY_RE.test(text.slice(0, 4000))
}

// ---------------------------------------------------------------------------
// De-duplication fingerprinting (shared with panel.js so there is exactly
// one definition of "what counts as the same request").
// ---------------------------------------------------------------------------

const SENSITIVE_HEADER_RE = /^(cookie|set-cookie|authorization|proxy-authorization)$/i
const SENSITIVE_HEADER_HINT_RE = /(csrf|xsrf|token|api-key|secret)/i
const VOLATILE_FIELD_RE = /(^|[-_])(csrf|xsrf|token|nonce|timestamp|ts|session|sessionid|access[-_]?token|refresh[-_]?token|authenticity[-_]?token)($|[-_])/i

export function isSensitiveHeaderName(name) {
  return SENSITIVE_HEADER_RE.test(name) || SENSITIVE_HEADER_HINT_RE.test(name)
}
export function isVolatileFieldName(name) { return VOLATILE_FIELD_RE.test(name) }

/** Request body with volatile fields (CSRF tokens, nonces, …) masked so the fingerprint is stable across otherwise-identical requests. */
export function normalizedRequestBody(postData) {
  const raw = postData?.text || ''
  const mime = (postData?.mimeType || '').toLowerCase()
  if (mime.includes('json')) {
    try {
      const walk = value => {
        if (Array.isArray(value)) return value.map(walk)
        if (value && typeof value === 'object') {
          return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, isVolatileFieldName(k) ? '{volatile}' : walk(v)]))
        }
        return value
      }
      return JSON.stringify(walk(JSON.parse(raw)))
    } catch { return raw }
  }
  if (mime.includes('application/x-www-form-urlencoded')) {
    const form = new URLSearchParams(raw)
    for (const name of form.keys()) if (isVolatileFieldName(name)) form.set(name, '{volatile}')
    form.sort()
    return form.toString()
  }
  return raw
}

/** URL with volatile query values masked, hash stripped. */
export function fingerprintURL(raw) {
  const u = new URL(raw)
  for (const name of u.searchParams.keys()) if (isVolatileFieldName(name)) u.searchParams.set(name, '{volatile}')
  u.hash = ''
  return u.toString()
}

/**
 * Canonical string identifying "this request, from this identity" for
 * de-duplication. The identity label is deliberately part of the
 * fingerprint: the exact same request replayed under a *different*
 * identity label is new cross-identity evidence, never a duplicate to
 * collapse away — collapsing it would silently blind the triage engine
 * whenever a tester repeats a flow after switching identity, which is
 * precisely the workflow this tool exists to support.
 */
export function fingerprintInput({ method, url, headers, postData, identityLabel }) {
  const stableHeaders = (headers || [])
    .map(h => [String(h.name).toLowerCase(), isSensitiveHeaderName(h.name) ? '{secret}' : (h.value || '')])
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
  return JSON.stringify([identityLabel || '', method, fingerprintURL(url), stableHeaders, normalizedRequestBody(postData)])
}

export const TIERS = [
  { value: '', label: 'Unset' },
  { value: '0', label: 'Anonymous' },
  { value: '1', label: 'Low-priv' },
  { value: '2', label: 'Standard user' },
  { value: '3', label: 'Elevated' },
  { value: '4', label: 'Admin' },
]

function severityRank(s) { return s === 'high' ? 2 : s === 'medium' ? 1 : 0 }

/**
 * Incremental cross-identity triage engine. Feed it one captured entry at a
 * time (in capture order); it maintains small per-template / per-object
 * indices so cost per entry stays ~O(identities-on-that-endpoint), not
 * O(total captured entries).
 */
export class TriageEngine {
  constructor(config = {}) {
    this.extraIdParams = new Set((config.extraIdParams || []).map(s => s.toLowerCase()))
    this.sensitivePatterns = (config.sensitivePatterns || []).filter(Boolean)
    this.tiers = new Map(Object.entries(config.tiers || {}))
    this.objectIndex = new Map()   // concreteKey -> Map(identityLabel -> sighting)
    this.templateIndex = new Map() // templateKey  -> Map(identityLabel -> sighting)
    this.findings = new Map()      // findingKey   -> finding
    this.identities = new Map()    // label -> {count, firstSeen, lastSeen}
  }

  setTier(label, tier) {
    if (tier === '' || tier == null) this.tiers.delete(label)
    else this.tiers.set(label, Number(tier))
  }
  setExtraIdParams(list) { this.extraIdParams = new Set((list || []).map(s => s.trim().toLowerCase()).filter(Boolean)) }
  setSensitivePatterns(list) { this.sensitivePatterns = (list || []).map(s => s.trim()).filter(Boolean) }

  /** Returns the configured pattern that matched, or null. `/regex/flags` syntax is supported; anything else is a case-insensitive substring match. */
  matchedSensitivePattern(pathname) {
    for (const p of this.sensitivePatterns) {
      if (p.length > 2 && p.startsWith('/') && p.lastIndexOf('/') > 0) {
        const cut = p.lastIndexOf('/')
        try {
          if (new RegExp(p.slice(1, cut), p.slice(cut + 1)).test(pathname)) return p
          continue
        } catch { /* fall through to substring match on a malformed regex */ }
      }
      if (pathname.toLowerCase().includes(p.toLowerCase())) return p
    }
    return null
  }

  /**
   * Ingest one captured entry. `rawResponseText` is the decoded (not
   * base64) response body, bounded by the caller — pass '' / undefined if
   * unavailable (e.g. the body was too large to fetch). Returns the list of
   * *newly created* findings (already-seen findings are updated in place
   * but not returned, so callers can use this for incremental notification
   * as well as a full re-render).
   */
  ingest(entry, rawResponseText) {
    const created = []
    let url
    try { url = new URL(entry.request.url) } catch { return created }
    const identity = (entry.identity_label || '').trim() || 'unlabeled'
    this._touchIdentity(identity, entry.started_at)

    const tmpl = `${entry.request.method} ${templatePath(url.pathname)}`
    const bodyLen = rawResponseText != null ? rawResponseText.length : (entry.response.size || 0)
    const outcome = classifyOutcome(entry.response.status, bodyLen, rawResponseText)
    const bodyMime = entry.response.mime_type || ''

    let byIdentity = this.templateIndex.get(tmpl)
    if (!byIdentity) { byIdentity = new Map(); this.templateIndex.set(tmpl, byIdentity) }
    byIdentity.set(identity, { url: url.toString(), status: entry.response.status, outcome, at: entry.started_at })

    // ---- object-level: same concrete resource reached by 2+ identities ----
    const idSignals = [
      ...new Set([
        ...pathIdSegments(url.pathname),
        ...queryIdSignals(url.searchParams, this.extraIdParams),
        ...bodyIdSignals(rawResponseText, bodyMime, this.extraIdParams),
      ]),
    ]
    if (idSignals.length) {
      const concreteKey = `${tmpl}::${idSignals.sort().join('&')}`
      let byId = this.objectIndex.get(concreteKey)
      if (!byId) { byId = new Map(); this.objectIndex.set(concreteKey, byId) }
      byId.set(identity, { url: url.toString(), status: entry.response.status, outcome, at: entry.started_at, len: bodyLen })

      if (byId.size >= 2) {
        const succeeded = [...byId.entries()].filter(([, v]) => v.outcome === 'success')
        if (succeeded.length >= 2) {
          const f = this._upsertFinding('object_idor', concreteKey, {
            severity: 'high',
            title: 'Two identities both reached the same object',
            hint: 'Confirm neither identity legitimately owns/shares this object, then replay in Guided Analyze to prove it.',
            template: tmpl,
            objectSignals: idSignals,
            sensitive: looksSensitiveBody(rawResponseText),
          }, succeeded.map(([label, v]) => ({ label, ...v })))
          if (f) created.push(f)
        }
      }
    }

    // ---- configured: a captured request hit a sensitive/admin-ish path and succeeded ----
    const matchedPattern = this.sensitivePatterns.length ? this.matchedSensitivePattern(url.pathname) : null
    if (matchedPattern && outcome === 'success') {
      const tier = this.tiers.has(identity) ? this.tiers.get(identity) : null
      const maxTier = this._maxConfiguredTier()
      const severity = tier != null && maxTier != null && tier < maxTier ? 'high' : 'medium'
      const f = this._upsertFinding('sensitive_path', `${identity}::${tmpl}`, {
        severity,
        title: 'Success response on a configured sensitive path',
        hint: `Matched pattern "${matchedPattern}". Verify this identity is meant to reach it.`,
        template: tmpl,
        pattern: matchedPattern,
      }, [{ label: identity, tier, url: url.toString(), status: entry.response.status, outcome, at: entry.started_at }])
      if (f) created.push(f)
    }

    // ---- configured: a lower-tier identity succeeded where a higher-tier identity is also seen (BFLA candidate) ----
    if (this.tiers.size >= 2) {
      for (const [lowLabel, lowRec] of byIdentity.entries()) {
        if (!this.tiers.has(lowLabel) || lowRec.outcome !== 'success') continue
        const lowTier = this.tiers.get(lowLabel)
        for (const [highLabel, highRec] of byIdentity.entries()) {
          if (highLabel === lowLabel || !this.tiers.has(highLabel)) continue
          const highTier = this.tiers.get(highLabel)
          if (highTier <= lowTier) continue
          const key = `${tmpl}::${[lowLabel, highLabel].sort().join('|')}`
          const f = this._upsertFinding('cross_tier_function', key, {
            severity: 'medium',
            title: 'Lower-tier identity succeeded on an endpoint a higher-tier identity also uses',
            hint: 'Function-level (BFLA) candidate — confirm the lower tier is actually meant to reach this endpoint.',
            template: tmpl,
          }, [
            { label: lowLabel, tier: lowTier, ...lowRec },
            { label: highLabel, tier: highTier, ...highRec },
          ])
          if (f) created.push(f)
        }
      }
    }

    return created
  }

  _maxConfiguredTier() {
    if (!this.tiers.size) return null
    return Math.max(...this.tiers.values())
  }

  _touchIdentity(label, at) {
    const rec = this.identities.get(label) || { count: 0, firstSeen: at, lastSeen: at }
    rec.count++
    rec.lastSeen = at
    this.identities.set(label, rec)
  }

  _upsertFinding(category, key, meta, evidence) {
    const findingKey = `${category}:${key}`
    const existing = this.findings.get(findingKey)
    if (existing) {
      existing.hitCount++
      existing.lastSeen = evidence[evidence.length - 1]?.at || existing.lastSeen
      existing.evidence = evidence
      // Refresh derived fields (severity in particular): a tester can set
      // role tiers or add a sensitive-path pattern *after* traffic was
      // already captured, and re-ingesting that traffic (see panel.js
      // reanalyzeAll) must let a re-sighted finding pick up the new
      // severity instead of being stuck with whatever it was computed as
      // the first time, before any config existed.
      Object.assign(existing, meta)
      return null
    }
    const finding = {
      id: findingKey,
      category,
      hitCount: 1,
      firstSeen: evidence[0]?.at,
      lastSeen: evidence[evidence.length - 1]?.at,
      evidence,
      ...meta,
    }
    this.findings.set(findingKey, finding)
    return finding
  }

  list() {
    return [...this.findings.values()].sort(
      (a, b) => severityRank(b.severity) - severityRank(a.severity) || String(b.lastSeen || '').localeCompare(String(a.lastSeen || ''))
    )
  }

  identitySummary() {
    return [...this.identities.entries()].map(([label, v]) => ({
      label, tier: this.tiers.has(label) ? this.tiers.get(label) : '', ...v,
    }))
  }

  reset() {
    this.objectIndex.clear()
    this.templateIndex.clear()
    this.findings.clear()
    this.identities.clear()
  }
}
