package scanner

import (
	"context"
	"io"
	"net/http"
	"strings"
	"time"
)

// WAF / bot-challenge / block-page detection.
//
// The #1 way a differential injection check turns into a false positive is a
// security intermediary (Cloudflare, Akamai, Imperva/Incapsula, F5 BIG-IP ASM,
// AWS WAF, ModSecurity, Sucuri, Wordfence…) answering the INJECTED request with a
// block or challenge page instead of the application. Those pages routinely carry
// a per-request Ray ID / incident ID / timestamp, so two "identical" blocked
// responses differ by a few hundred bytes — exactly the signal a boolean/length
// differential reads as "the payload changed the query". They also add latency,
// which a naive time-based check reads as a SLEEP. Recognising a block page and
// refusing to derive a finding from it removes that whole FP class.
//
// The signatures below are deliberately SPECIFIC vendor strings, not generic
// words like "forbidden" (which appear on legitimate 403 pages), so a match is a
// real security-intermediary block, not an ordinary application response.

var wafBlockBodySignatures = []string{
	// Cloudflare
	"attention required! | cloudflare", "cloudflare ray id", "cf-ray",
	"checking your browser before accessing", "just a moment...",
	"please turn javascript on and reload the page", "cf-chl", "__cf_chl",
	"performance & security by cloudflare", "ray id:",
	// Akamai
	"access denied", "reference&#32;#", "you don't have permission to access",
	"akamaighost", "errors.edgesuite.net",
	// Imperva / Incapsula
	"request unsuccessful. incapsula incident id", "_incapsula_resource",
	"powered by incapsula", "imperva",
	// F5 BIG-IP ASM
	"the requested url was rejected. please consult with your administrator",
	// ModSecurity / generic mod_security
	"mod_security", "modsecurity", "this error was generated by mod_security",
	"not acceptable!", "406 not acceptable",
	// Sucuri
	"sucuri website firewall", "access denied - sucuri website firewall",
	"cloudproxy", "sucuri/cloudproxy",
	// Wordfence
	"generated by wordfence", "your access to this site has been limited",
	// Barracuda / Fortinet / others
	"barracuda", "fortiweb", "web application firewall",
	"your request has been blocked", "this request has been blocked",
	"has been blocked by the security policy", "blocked by the security rules",
	// Distil / PerimeterX / DataDome bot managers
	"distil", "px-captcha", "perimeterx", "datadome", "captcha-delivery.com",
}

// looksLikeWAFBlock reports whether an HTTP response is a WAF / bot-challenge /
// rate-limit block rather than a genuine application response. A status of 429
// (rate limited) or 406 (ModSecurity's default deny) is a block on its own; any
// other status is a block only when the body carries a specific vendor
// block-page signature. Pass status 0 when the caller only has the body.
func looksLikeWAFBlock(status int, body string) bool {
	if status == 429 || status == 406 {
		return true
	}
	if body == "" {
		return false
	}
	lb := strings.ToLower(body)
	for _, sig := range wafBlockBodySignatures {
		if strings.Contains(lb, sig) {
			return true
		}
	}
	return false
}

// bodyLooksLikeWAFBlock is the body-only form for callers that don't have the
// status code (e.g. anything built on sendInjected).
func bodyLooksLikeWAFBlock(body string) bool { return looksLikeWAFBlock(0, body) }

// ── Named WAF / edge fingerprinting (which vendor, shown in the HTTP tab) ─────
//
// Separate from looksLikeWAFBlock (which only asks "is this a block page?"): this
// identifies WHICH WAF/CDN fronts a host from its normal response — a proprietary
// header, Set-Cookie name, Server banner or block-page string. PASSIVE (one plain
// GET, no attack payloads) and matched only on vendor-specific signals, so a hit
// is real, not a guess.

var wafFingerprintClient = &http.Client{
	Timeout:   10 * time.Second,
	Transport: sharedHTTPTransport,
	CheckRedirect: func(_ *http.Request, via []*http.Request) error {
		if len(via) >= 3 {
			return http.ErrUseLastResponse
		}
		return nil
	},
}

type wafSig struct {
	name    string
	headers map[string]string // header (lowercase) -> value substring ("" = presence is enough)
	cookies []string          // Set-Cookie name substrings
	server  []string          // Server-header substrings
	body    []string          // body substrings (block pages etc.)
}

// wafSignatures — ordered; first match wins. Each uses a vendor-specific signal.
var wafSignatures = []wafSig{
	{name: "Cloudflare", headers: map[string]string{"cf-ray": "", "cf-cache-status": ""}, server: []string{"cloudflare"}, cookies: []string{"__cfduid", "__cf_bm", "cf_clearance"}},
	{name: "Akamai", headers: map[string]string{"x-akamai-transformed": "", "akamai-grn": ""}, server: []string{"akamaighost"}, cookies: []string{"ak_bmsc", "bm_sz"}},
	{name: "Imperva Incapsula", headers: map[string]string{"x-iinfo": "", "x-cdn": "incapsula"}, cookies: []string{"incap_ses", "visid_incap", "nlbi_"}, body: []string{"powered by incapsula", "incapsula incident id"}},
	{name: "AWS WAF / CloudFront", headers: map[string]string{"x-amz-cf-id": "", "x-amz-cf-pop": ""}, server: []string{"awselb", "cloudfront"}, cookies: []string{"aws-waf-token", "awsalb"}},
	{name: "Sucuri", headers: map[string]string{"x-sucuri-id": "", "x-sucuri-cache": ""}, server: []string{"sucuri"}, body: []string{"sucuri website firewall"}},
	{name: "F5 BIG-IP ASM", cookies: []string{"bigipserver", "ts01"}, body: []string{"the requested url was rejected"}},
	{name: "Fastly", headers: map[string]string{"x-fastly-request-id": ""}, server: []string{"fastly"}},
	{name: "StackPath", server: []string{"stackpath"}},
	{name: "Barracuda", cookies: []string{"barra_counter_session", "bni__barracuda"}},
	{name: "FortiWeb", cookies: []string{"fortiwafsid"}, server: []string{"fortiweb"}},
	{name: "Citrix NetScaler", cookies: []string{"ns_af", "citrix_ns_id"}, headers: map[string]string{"via": "ns-cache"}},
	{name: "ModSecurity", server: []string{"mod_security", "modsecurity"}, body: []string{"this error was generated by mod_security"}},
	{name: "Wordfence", body: []string{"generated by wordfence"}},
	{name: "DDoS-Guard", server: []string{"ddos-guard"}, cookies: []string{"__ddg"}},
	{name: "Reblaze", cookies: []string{"rbzid"}},
	{name: "Wallarm", headers: map[string]string{"x-wallarm-": ""}},
	{name: "Azure Front Door / App Gateway", headers: map[string]string{"x-azure-ref": ""}, server: []string{"microsoft-azure-application-gateway"}},
	{name: "PerimeterX / DataDome", cookies: []string{"_px", "datadome"}, body: []string{"px-captcha", "captcha-delivery.com"}},
}

func (s wafSig) match(hdr map[string]string, server, cookies, body string) bool {
	for h, val := range s.headers {
		if v, ok := hdr[h]; ok && (val == "" || strings.Contains(v, val)) {
			return true
		}
	}
	for _, c := range s.cookies {
		if strings.Contains(cookies, c) {
			return true
		}
	}
	for _, sv := range s.server {
		if strings.Contains(server, sv) {
			return true
		}
	}
	for _, b := range s.body {
		if strings.Contains(body, b) {
			return true
		}
	}
	return false
}

// detectWAF returns the name of the WAF/edge fronting rawURL, or "" if none is
// fingerprinted. Best-effort, non-intrusive (a single benign GET).
func detectWAF(ctx context.Context, rawURL string) string {
	cctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(cctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return ""
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36")
	resp, err := wafFingerprintClient.Do(req)
	if err != nil {
		return ""
	}
	defer resp.Body.Close()

	hdr := make(map[string]string, len(resp.Header))
	for k, v := range resp.Header {
		if len(v) > 0 {
			hdr[strings.ToLower(k)] = strings.ToLower(strings.Join(v, "; "))
		}
	}
	server := hdr["server"]
	cookies := strings.ToLower(strings.Join(resp.Header.Values("Set-Cookie"), "; "))
	bodyBytes, _ := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	body := strings.ToLower(string(bodyBytes))

	for _, sig := range wafSignatures {
		if sig.match(hdr, server, cookies, body) {
			return sig.name
		}
	}
	return ""
}
